### ISSUE TITLE
API Fetch Standings

### ISSUE THREAD

**Issue by carmopereira** [barneycg/temars-eve-api#9]
TEA 1.3.1 r2

eve standing api now gives me an error:
API System Screwed - Can't fetch Toons : bool(false) API System Screwed - Can't Fetch Standings : bool(false) There is a problem fetching Standings : int(9999) 

What kind of api should be used? character, corp? can you get me a example mask?

**Comment by barneycg** [comment]
Personally I use a corp key with the Standings option selected.  You want to get the corps standings so it can work out if someone is Red or Blue :)

That error is indicative of a failure to actually communicate with CCP's servers ... I don't know how many people are running this latest version but you are the second person to send me exactly the same error which makes me a tad concerned though I don't see it at all in my test systems

**Comment by carmopereira** [comment]
I had to put the old version, because all api was broken. and no one can register on jabber also., and the "full member check" was broken also.

**Comment by barneycg** [comment]
So the next question is why is the api fetching broken completely for you ... I've literally just reinstalled the version I posted up and it works fine for me.  The error messages you've posted would only occur if when you try and fetch the api page in question CCP's servers give you back a bad response.
The response must either timeout or contain the words/phrases "runtime", "The service is unavailable", "404 Not Found"
It can't be that you don't have curl installed because you'd have problems on the old version and you would get a different error message.

**Comment by carmopereira** [comment]
when you replace the files by the new ones, you need to run some update? or dbupdate?

**Comment by barneycg** [comment]
Nope.  What version were you coming from ?  How did you upgrade ?  I uninstall, delete files, then install the new version.

**Comment by carmopereira** [comment]
just upgraded, all works.
